### ISSUE TITLE
charts/template/local-storage-csi-sidecar.yaml

### ISSUE THREAD

**Issue by jiuker** [hwameistor/helm-charts#10]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwameistor-csi-controller 
  namespace: {{ .Release.Namespace}}
spec:
  replicas: {{ .Values.csidriver.replicas}}
  selector:
    matchLabels:
      app: hwameistor-csi-controller
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hwameistor-csi-controller
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hwameistor
            topologyKey: localstorage.hwameistor.io/local-storage-topology-node
      containers:
      - args:
        - --v=5
        - --csi-address=$(CSI_ADDRESS)
        - --leader-election=true
        - --feature-gates=Topology=true
        - --strict-topology
        env:
        - name: CSI_ADDRESS
          value: /csi/csi.sock
        image: {{ .Values.csidriver.provisioner.image}}
        imagePullPolicy: IfNotPresent
        name: provisioner
        resources:
          limits:
            cpu: {{ .Values.csidriver.provisioner.resources.limits.cpu}}
            memory: {{ .Values.csidriver.provisioner.resources.limits.memory}}
          requests:
            cpu: {{ .Values.csidriver.provisioner.resources.requests.cpu}}
            memory: {{ .Values.csidriver.provisioner.resources.requests.memory}}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
        - --v=5
        - --csi-address=$(CSI_ADDRESS)
        - --leader-election=true
        - --timeout=120s
        env:
        - name: CSI_ADDRESS
          value: /csi/csi.sock
        image: {{ .Values.csidriver.attacher.image}}
        imagePullPolicy: IfNotPresent
        name: attacher
        resources:
          limits:
            cpu: {{ .Values.csidriver.attacher.resources.limits.cpu}}
            memory: {{ .Values.csidriver.attacher.resources.limits.memory}}
          requests:
            cpu: {{ .Values.csidriver.attacher.resources.requests.cpu}}
            memory: {{ .Values.csidriver.attacher.resources.requests.memory}}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
        - --v=5
        - --csi-address=$(CSI_ADDRESS)
        - --leader-election=true
        env:
        - name: CSI_ADDRESS
          value: /csi/csi.sock
        image: {{ .Values.csidriver.resizer.image}}
        imagePullPolicy: IfNotPresent
        name: resizer
        resources:
          limits:
            cpu: {{ .Values.csidriver.resizer.resources.limits.cpu}}
            memory: {{ .Values.csidriver.resizer.resources.limits.memory}}
          requests:
            cpu: {{ .Values.csidriver.resizer.resources.requests.cpu}}
            memory: {{ .Values.csidriver.resizer.resources.requests.memory}}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      dnsPolicy: ClusterFirst
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      serviceAccountName: hwameistor-admin 
      serviceAccount: hwameistor-admin
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/localstorage.hwameistor.io
          type: DirectoryOrCreate
        name: socket-dir
```
spec.template.spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].labelSelector
Why app is in 'hwameistor',not in 'hwameistor-csi-controller'.Because Deployment defined labels is 'app: hwameistor-csi-controller',I couldn't undestand。
