### ISSUE TITLE
How to enable high availability？

### ISSUE THREAD

**Issue by xulongju** [hwameistor/helm-charts#12]
Hi，
How to enable high availability？

**Comment by niulechuan** [comment]
For current release:
1. Install DRBD on your host (https://github.com/LINBIT/drbd)
2. Apply a StorageClass with HA configurations.
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-hdd-lvm
provisioner: localstorage.hwameistor.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  replicaNumber: "2"
  poolClass: "HDD"
  poolType: "REGULAR"
  volumeKind: "LVM"
  striped: "true"
  csi.storage.k8s.io/fstype: "xfs"
```
